"""empty message

Revision ID: 972fe7f1109f
Revises: 9ddfafcf023c
Create Date: 2023-03-01 01:57:14.237772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972fe7f1109f'
down_revision = '9ddfafcf023c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('class_style', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'class_style')
    # ### end Alembic commands ###
