"""empty message

Revision ID: 9ddfafcf023c
Revises: c75e7473ae44
Create Date: 2023-02-28 06:31:54.838923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddfafcf023c'
down_revision = 'c75e7473ae44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('is_console', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'is_console')
    # ### end Alembic commands ###
