"""empty message

Revision ID: a8f8ed2fb7b8
Revises: 9ddfafcf023c
Create Date: 2023-03-02 15:46:09.944492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f8ed2fb7b8'
down_revision = '9ddfafcf023c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('class_style', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'class_style')
    # ### end Alembic commands ###
