"""empty message

Revision ID: c75e7473ae44
Revises: a7eb5f82921e
Create Date: 2023-02-28 04:29:38.719543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75e7473ae44'
down_revision = 'a7eb5f82921e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('banner', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'banner')
    # ### end Alembic commands ###
